version: '3.0'

volumes:
    data: {}
services:
    #    mariadb:
    #        build:
    #            context: ./mariadb
    #            dockerfile: mariadb.dockerfile
    #        expose:
    #            - "3306"
    #        networks:
    #            - intra
    #        tty: true
    #    nginx:
    #        build:
    #            context: ./nginx
    #            dockerfile: nginx.dockerfile
    #        ports:
    #            - 80:80
    #        networks:
    #            - intra
    #        tty: true
    db:
        image: mysql:5.7
        platform: linux/x86_64
        volumes:
            - data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
    wordpress:
        build:
            context: ./wordpress
            dockerfile: wordpress.dockerfile

        volumes:
            - data:/var/www/html
        ports:
            - "8000:80"
        restart: always
        tty: true
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
              #        expose:
              #            - "9000"
              #        networks:
              #            - intra
              #        tty: true
              #networks:
              #    intra:
              #        driver: bridge
