version: '3.0'

volumes:
    data: {}
services:
    mariadb:
        build:
            context: ./mariadb
            args:
                WP_DATABASE_NAME: ${WP_DATABASE_NAME}
                WP_DATABASE_USR: ${WP_DATABASE_USR}
                WP_DATABASE_PWD: ${WP_DATABASE_PWD}
            dockerfile: mariadb.dockerfile
        expose:
            - "3306"
        networks:
            - intra
        tty: true
        stdin_open: true
        env_file: .env
    nginx:
        build:
            context: ./nginx
            dockerfile: nginx.dockerfile
        volumes:
            - data:/var/www/html
        ports:
            - 443:443
        networks:
            - intra
        tty: true
        stdin_open: true
        env_file: .env
    wordpress:
        build:
            context: ./wordpress
            dockerfile: wordpress.dockerfile
        volumes:
            - data:/var/www/html
        expose:
            - "9000"
        networks:
            - intra
        tty: true
        stdin_open: true
        env_file: .env
networks:
    intra:
        driver: bridge
