version: '3.0'

volumes:
    db_data: {}
    wp_data: {}
services:
    #    mariadb:
    #        build:
    #            context: ./mariadb
    #            dockerfile: mariadb.dockerfile
    #        expose:
    #            - "3306"
    #        networks:
    #            - intra
    #        tty: true
    #    nginx:
    #        build:
    #            context: ./nginx
    #            dockerfile: nginx.dockerfile
    #        ports:
    #            - 80:80
    #        networks:
    #            - intra
    #        tty: true
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        networks:
            - intra
    wordpress:
        depends_on:
            - db
        build:
            context: ./wordpress
            dockerfile: wordpress.dockerfile
        volumes:
            - wp_data:/var/www/html
        ports:
            - "8000:80" 
        networks:
            - intra
        tty: true
        environment:
             WORDPRESS_DB_HOST: db
             WORDPRESS_DB_USER: wordpress
             WORDPRESS_DB_PASSWORD: wordpress
             WORDPRESS_DB_NAME: wordpress 
          #        stdin_open: true
networks:
    intra:
        driver: bridge
