CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'yubae'@'%' IDENTIFIED BY '0000';
GRANT ALL PRIVILEGES ON wordpress.* TO 'yubae'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '0000';
