service mysql start
mysql -e "CREATE DATABASE $WP_DATABASE_NAME;"
mysql -e "CREATE USER '$WP_DATABASE_USR'@'%' IDENTIFIED BY '$WP_DATABASE_PWD';"
mysql -e "GRANT ALL ON $WP_DATABASE_NAME.* TO '$WP_DATABASE_USR'@'%';"
mysql -e "FLUSH PRIVILEGES;"
