version: '3.0'
services:
    nginx:
        build:
            context: ./requirements/nginx
            dockerfile: nginx.dockerfile
        ports:
            - 443:443
        volumes:
            - "wordpress:/var/www/html"
        networks:
            - intra
        restart: always
    
    wordpress:
        build:
            context: ./requirements/wordpress
            dockerfile: wordpress.dockerfile
        volumes:
            - "wordpress:/var/www/html"
        depends_on:
            - mariadb
        networks:
            - intra
        restart: always
        env_file: .env
    mariadb:
        build:
            context: ./requirements/mariadb
            dockerfile: mariadb.dockerfile
        environment:
            - MYSQL_ROOT__PWD=${MYSQL_ROOT_PWD}
            - WP_DATABASE_NAME=${WP_DATABASE_NAME}
            - WP_DATABASE_USR=${WP_DATABASE_USR}
            - WP_DATABASE_PWD=${WP_DATABASE_PWD}
        volumes:
            - "mariadb:/var/lib/mysql"
        networks:
            - intra
        restart: always
        env_file: .env

volumes:
    mariadb:
        driver: local
        driver_opts:
            type: none
            device: /home/yubae/data/mariadb
            o: bind
    wordpress:
        driver: local
        driver_opts:
            type: none
            device: /home/yubae/data/wordpress
            o: bind
networks:
    intra:
