CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY '0000';
GRANT ALL PRIVILEGES ON wordpress.* TO 'user'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '0000';
