version: '3.0'

volumes:
    data: {}
services:
    #    mariadb:
    #        build:
    #            context: ./mariadb
    #            dockerfile: mariadb.dockerfile
    #        expose:
    #            - "3306"
    #        networks:
    #            - intra
    #        tty: true
    nginx:
        build:
            context: ./nginx
            dockerfile: nginx.dockerfile
        ports:
            - 80:80
        networks:
            - intra
        tty: true
    wordpress:
        build:
            context: ./wordpress
            dockerfile: wordpress.dockerfile
        volumes:
            - data:/var/www/html
        expose:
            - "9000"
        networks:
            - intra
        tty: true
          #        stdin_open: true
networks:
    intra:
        driver: bridge
